language: node_js
node_js:
- node
deploy:
  provider: npm
  email: npmjs@solsort.com
  api_key:
    secure: HWWEE50OzaKeUrE9ctf7FyrBc7luhju6FrIOSqTgbeMrIdM2aZ4wYr4aC9pWo3KR2D1Si4Ff8l055+k7c2f6jiblwJU04SMD3gsew7FDDSJdELfkmtpjIjUn720QlRYr+ecQ2oOsRSR8HGdyW+uDjZUTgonOW2ysxdO3i8BRqKS1fjUEK1zbmzMIGmEx/HoPokboPbbYGC6HcJddXFvlkw1TFOWD98rXmjkXaOeQQGVqrA9g7fwrsNRdvnBQn+ipKJ8oBPFrYmsmoSu2M+OgYUSXlM1y86tA8UhNwqs8kT7O1kc41X2NndH3OJ8P4zvJhGVTfa1/yA2tAMYUef3/84+N6b7rASButwyrfhYKWo0hTF8nqy07EVSro0fbRQM/bIfpJKDRNHsY/G4afzAGGOT6v5lUVQ9dM2DAoxq2c+nVH1TZUz8IlqUePycHIWUkEz7Dbi6zvj129KfcVHiGtjWFWUkbhEz3iBPlRHl9sbPUQlqtxxuWKjcWFFdhW309k+Br7DcsMb/cVEloTDzxygdtbIYn40kwLw7nUaGJOeouAdz2A7jgC6VgvjY649dbwJfqwg7+LUJAlyUMfVJcrf/VS4HKfbd0ncoGhPzM3DmEyUu2IwAwnbKDl97DCpdrowIxdmT0PFjvo4Fdlds9gWsF0W8wzTXrGLnHnL9/7mM=
  on:
    repo: solsort/simple-javascript
